### PR TITLE
Add Asuswrt-Merlin to custom firmware section

### PR DESCRIPTION
**Pull request by Kojoley**

### CODE REVIEW

**Comment by Kojoley** [comment]
List rendering is broken on the site :(
[Github renders it correctly](https://github.com/tohojo/bufferbloat-net/blob/master/content/bloat/wiki/What_can_I_do_about_Bufferbloat.md).

**Comment by tohojo** [comment]
Alright, reverted. Please resubmit a working version (probably some markdown dialect issue)...

**Comment by Kojoley** [comment]
I have no idea how to test. The first five "markdown online preview" found on google - all render it correctly.

**Comment by Kojoley** [comment]
According to https://gohugo.io/getting-started/configuration-markup/ it uses [Goldmark](https://github.com/yuin/goldmark/) dialect, there is [a link to online previewer](https://yuin.github.io/goldmark/playground/) and it... renders correctly. I have no clue what's wrong. Which dialect is the site configured to?

**Pull request merged**
