### PR TITLE
Add RRUL Spec to bloat wiki

### PR DESCRIPTION
**Pull request by richb-hanover**

### CODE REVIEW

**Comment by tohojo** [comment]
The history is all messed up here. Think you need to rebase.

To avoid these issues, it is a good idea to create a new branch each time you make changes that result in a pull request. Then you can simply delete the branch once the pull request is merged, and keep your master branch in sync with upstream. :)

**Comment by richb-hanover** [comment]
Also added a page explaining the RRUL charts, which I found to be inscrutable for a while. This is only the briefest explanation - the page needs to talk about BK, BE, CS5, EF, etc. for those who are unhealthily interested in this stuff :-)

**Comment by tohojo** [comment]
Awesome! But this pull request can't be merged in its current stage. You need to rebase and only include the relevant changes...

**Comment by richb-hanover** [comment]
Superseded by PR of 6Jul2016. Closing this one

**Pull request closed without merging**
