### PR TITLE
Remove dslreports.com/speedtest from list of tests

### PR DESCRIPTION
**Pull request by whereami8224**
Unfortunately, dslreports.com's speed test seems to be non-functional and defunct.

https://www.dslreports.com/forum/r33240157-Speed-Test-Servers-Status

### CODE REVIEW

**Comment by tohojo** [comment]
Oh, that's sad :(
Guess we can always put it back if it recovers, so I'm okay with merging this now...

@richb-hanover @dtaht any objections?

**Review by tohojo — APPROVED** [review]

**Comment by richb-hanover** [comment]
No objections. But sad, indeed.  (I wrote to Jonathan Foulkes to see if he has any insight - the IQrouter ads are still running. I'll let you know if I hear anything.)

But we can probably merge - that site is clearly not working now.

**Comment by richb-hanover** [comment]
BTW: There are a bunch of references to DSLReports - see https://github.com/tohojo/bufferbloat-net/search?q=dslreports

**Comment by tohojo** [comment]
@whereami8224 care to update the other references as well while you're at it? I guess we could just switch them to the waveform test instead...

**Comment by whereami8224** [comment]
Sure, Done. I left alone `Daves_Media_Guidance.md` and the CSV files in `export`.

**Comment by tohojo** [comment]
Awesome, thanks!

**Pull request merged**
