### PR TITLE
Update site 

### PR DESCRIPTION
**Pull request by richb-hanover**
Improve What to do about Bufferbloat page
Deprecate /cerowrt/wiki branch of wiki
Pull (still) relevant pages into /bloat/wiki

### CODE REVIEW

**Comment by tohojo** [comment]
Should probably say Hugo 0.16 and not higher, now that newer versions are going to stay broken...

Will test that it builds on that version and then merge it... :)

**Comment by richb-hanover** [comment]
Are we stuck at Hugo 0.18? Or can we drop back to version 0.16?

In any event, I have raised a bug report on Hugo site, and also asked about workarounds on the Hugo discussion site. 

I suspect it's pretty straightforward (although agonizing) to fix. Just change:

- all links to full paths (add /cerowrt/wiki to the file name)
- s|.md|/|g for all links.

Yuck.

**Comment by tohojo** [comment]
We're stuck at 0.16. That is what the builder for the live site is running, anything newer is broken.

I'm not sure it's just a matter of changing prefixes. I think we need to switch to the other internal link syntax, which us awful... Or we could just stay on 0.16; there's no compelling reason to upgrade, really...

**Comment by tohojo** [comment]
As for the contents of this: Why do some of your links have target=_blank?

**Comment by richb-hanover** [comment]
target="_blank" (or target="anything") opens the linked page in a new tab/page, instead of replacing the current contents.

**Comment by tohojo** [comment]
Sure, but why are you doing that for links to the same site?

**Comment by richb-hanover** [comment]
I often do it for links from some main page, so that people can close all the sub-pages and still have see the main page.

But I see that I've done it inconsistently here, and it'll only happen on the main page (because it's HTML, not Markdown). So those should be removed for cross-site consistency.

**Comment by tohojo** [comment]
OK, I'll get rid of them while merging...

**Comment by richb-hanover** [comment]
Hmmm... After an hour of waiting (post-merge of my PR into master), the required checks haven't completed. Would you check? Thanks.

**Comment by tohojo** [comment]
That's because you merged it into the master branch of your own repository, not this one... ;)

Closed in c34a151

**Pull request closed without merging**
