### PR TITLE
Update/refactor [What to do about | Quick Test for ] Bufferbloat pages

### PR DESCRIPTION
**Pull request by richb-hanover**
Also remove "\\__" in favor of a simple "_" (e.g., fq\\_codel), change headings to use #, ## instead of underlining, etc.

### CODE REVIEW

**Comment by tohojo** [comment]
Looks good. Do you want to reinstate the link to the tuning session now that it works again?

Also, when changing the heading of the page it may be worth changing the filename (and thus the URL). The way to do this is renaming it with `git mv`, and adding an `aliases` section to the front matter - this needs to have the full previous URL to redirect from. See the issue pages for syntax...

**Comment by richb-hanover** [comment]
Good points. Watch for a new PR.

**Comment by tohojo** [comment]
You don't have to create a new PR - just pushing to the branch you created this one from will update it :)

**Comment by richb-hanover** [comment]
Updated tuning session link (and imported it from snapon, so that it's in easy version control). I'm done for a bit.

**Comment by tohojo** [comment]
Good work; I think there's a few tweaks needed before merging this (having a file called 'ipv6.svg' is bound to create problems later when it's just one flat namespace); can do those and merge it later...

**Pull request closed without merging**
